name: Build on MultiNet Container

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    container: felsokning/multinet:5ba85eb2e96185dd94f95e72daa84246b98fe83a
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: ls to see magics
        run: ls -a
      - name: .NET Restore
        run: dotnet restore --verbosity=normal
        working-directory: /__w/MultiNet-Example/MultiNet-Example
      - name: .NET Build
        run: dotnet build --verbosity=normal
        working-directory: /__w/MultiNet-Example/MultiNet-Example
      