name: Build on MultiNet Container

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    container: felsokning/multinet:latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: ls to see magics
        run: ls -a
      - name: .NET Restore
        run: dotnet restore --verbosity=normal
        working-directory: MuliNet.Example
      - name: .NET Build
        run: dotnet build --verbosity=normal
        working-directory: MuliNet.Example
      